// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: exchange.proto
#ifndef GRPC_exchange_2eproto__INCLUDED
#define GRPC_exchange_2eproto__INCLUDED

#include "exchange.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace exchange {

// The gRPC service definition
class ExchangeService final {
 public:
  static constexpr char const* service_full_name() {
    return "exchange.ExchangeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::exchange::Acknowledge* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>> AsyncSendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>>(AsyncSendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>> PrepareAsyncSendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>>(PrepareAsyncSendMessageRaw(context, request, cq));
    }
    virtual ::grpc::Status SendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::exchange::Acknowledge* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>> AsyncSendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>>(AsyncSendResponseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>> PrepareAsyncSendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>>(PrepareAsyncSendResponseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::exchange::MessageRequest>> RegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::exchange::MessageRequest>>(RegisterClientRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::MessageRequest>> AsyncRegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::MessageRequest>>(AsyncRegisterClientRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::MessageRequest>> PrepareAsyncRegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::MessageRequest>>(PrepareAsyncRegisterClientRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest* request, ::exchange::Acknowledge* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest* request, ::exchange::Acknowledge* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse* request, ::exchange::Acknowledge* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse* request, ::exchange::Acknowledge* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest* request, ::grpc::ClientReadReactor< ::exchange::MessageRequest>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>* AsyncSendMessageRaw(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>* PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>* AsyncSendResponseRaw(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::Acknowledge>* PrepareAsyncSendResponseRaw(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::exchange::MessageRequest>* RegisterClientRaw(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::exchange::MessageRequest>* AsyncRegisterClientRaw(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::exchange::MessageRequest>* PrepareAsyncRegisterClientRaw(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::exchange::Acknowledge* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>> AsyncSendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>>(AsyncSendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>> PrepareAsyncSendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>>(PrepareAsyncSendMessageRaw(context, request, cq));
    }
    ::grpc::Status SendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::exchange::Acknowledge* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>> AsyncSendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>>(AsyncSendResponseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>> PrepareAsyncSendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>>(PrepareAsyncSendResponseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::exchange::MessageRequest>> RegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::exchange::MessageRequest>>(RegisterClientRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::MessageRequest>> AsyncRegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::MessageRequest>>(AsyncRegisterClientRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::MessageRequest>> PrepareAsyncRegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::MessageRequest>>(PrepareAsyncRegisterClientRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest* request, ::exchange::Acknowledge* response, std::function<void(::grpc::Status)>) override;
      void SendMessage(::grpc::ClientContext* context, const ::exchange::MessageRequest* request, ::exchange::Acknowledge* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse* request, ::exchange::Acknowledge* response, std::function<void(::grpc::Status)>) override;
      void SendResponse(::grpc::ClientContext* context, const ::exchange::MessageResponse* request, ::exchange::Acknowledge* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RegisterClient(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest* request, ::grpc::ClientReadReactor< ::exchange::MessageRequest>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>* AsyncSendMessageRaw(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>* PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::exchange::MessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>* AsyncSendResponseRaw(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::Acknowledge>* PrepareAsyncSendResponseRaw(::grpc::ClientContext* context, const ::exchange::MessageResponse& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::exchange::MessageRequest>* RegisterClientRaw(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request) override;
    ::grpc::ClientAsyncReader< ::exchange::MessageRequest>* AsyncRegisterClientRaw(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::exchange::MessageRequest>* PrepareAsyncRegisterClientRaw(::grpc::ClientContext* context, const ::exchange::ClientRegistrationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendMessage_;
    const ::grpc::internal::RpcMethod rpcmethod_SendResponse_;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterClient_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendMessage(::grpc::ServerContext* context, const ::exchange::MessageRequest* request, ::exchange::Acknowledge* response);
    virtual ::grpc::Status SendResponse(::grpc::ServerContext* context, const ::exchange::MessageResponse* request, ::exchange::Acknowledge* response);
    virtual ::grpc::Status RegisterClient(::grpc::ServerContext* context, const ::exchange::ClientRegistrationRequest* request, ::grpc::ServerWriter< ::exchange::MessageRequest>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMessage(::grpc::ServerContext* context, ::exchange::MessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::exchange::Acknowledge>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendResponse() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SendResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendResponse(::grpc::ServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendResponse(::grpc::ServerContext* context, ::exchange::MessageResponse* request, ::grpc::ServerAsyncResponseWriter< ::exchange::Acknowledge>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterClient() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RegisterClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterClient(::grpc::ServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/, ::grpc::ServerWriter< ::exchange::MessageRequest>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterClient(::grpc::ServerContext* context, ::exchange::ClientRegistrationRequest* request, ::grpc::ServerAsyncWriter< ::exchange::MessageRequest>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendMessage<WithAsyncMethod_SendResponse<WithAsyncMethod_RegisterClient<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::exchange::MessageRequest, ::exchange::Acknowledge>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchange::MessageRequest* request, ::exchange::Acknowledge* response) { return this->SendMessage(context, request, response); }));}
    void SetMessageAllocatorFor_SendMessage(
        ::grpc::MessageAllocator< ::exchange::MessageRequest, ::exchange::Acknowledge>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchange::MessageRequest, ::exchange::Acknowledge>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendResponse() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::exchange::MessageResponse, ::exchange::Acknowledge>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchange::MessageResponse* request, ::exchange::Acknowledge* response) { return this->SendResponse(context, request, response); }));}
    void SetMessageAllocatorFor_SendResponse(
        ::grpc::MessageAllocator< ::exchange::MessageResponse, ::exchange::Acknowledge>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchange::MessageResponse, ::exchange::Acknowledge>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendResponse(::grpc::ServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendResponse(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RegisterClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterClient() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::exchange::ClientRegistrationRequest, ::exchange::MessageRequest>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchange::ClientRegistrationRequest* request) { return this->RegisterClient(context, request); }));
    }
    ~WithCallbackMethod_RegisterClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterClient(::grpc::ServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/, ::grpc::ServerWriter< ::exchange::MessageRequest>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::exchange::MessageRequest>* RegisterClient(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendMessage<WithCallbackMethod_SendResponse<WithCallbackMethod_RegisterClient<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendResponse() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SendResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendResponse(::grpc::ServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RegisterClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterClient() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RegisterClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterClient(::grpc::ServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/, ::grpc::ServerWriter< ::exchange::MessageRequest>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendResponse() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SendResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendResponse(::grpc::ServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendResponse(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterClient() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RegisterClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterClient(::grpc::ServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/, ::grpc::ServerWriter< ::exchange::MessageRequest>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterClient(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendResponse() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendResponse(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendResponse(::grpc::ServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendResponse(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterClient() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->RegisterClient(context, request); }));
    }
    ~WithRawCallbackMethod_RegisterClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterClient(::grpc::ServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/, ::grpc::ServerWriter< ::exchange::MessageRequest>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* RegisterClient(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::MessageRequest, ::exchange::Acknowledge>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchange::MessageRequest, ::exchange::Acknowledge>* streamer) {
                       return this->StreamedSendMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::exchange::MessageRequest* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::MessageRequest,::exchange::Acknowledge>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendResponse() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::MessageResponse, ::exchange::Acknowledge>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchange::MessageResponse, ::exchange::Acknowledge>* streamer) {
                       return this->StreamedSendResponse(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendResponse(::grpc::ServerContext* /*context*/, const ::exchange::MessageResponse* /*request*/, ::exchange::Acknowledge* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendResponse(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::MessageResponse,::exchange::Acknowledge>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendMessage<WithStreamedUnaryMethod_SendResponse<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_RegisterClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_RegisterClient() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::exchange::ClientRegistrationRequest, ::exchange::MessageRequest>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::exchange::ClientRegistrationRequest, ::exchange::MessageRequest>* streamer) {
                       return this->StreamedRegisterClient(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_RegisterClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterClient(::grpc::ServerContext* /*context*/, const ::exchange::ClientRegistrationRequest* /*request*/, ::grpc::ServerWriter< ::exchange::MessageRequest>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedRegisterClient(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::exchange::ClientRegistrationRequest,::exchange::MessageRequest>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_RegisterClient<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendMessage<WithStreamedUnaryMethod_SendResponse<WithSplitStreamingMethod_RegisterClient<Service > > > StreamedService;
};

}  // namespace exchange


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_exchange_2eproto__INCLUDED
