// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exchange.proto
// Protobuf C++ Version: 5.29.3

#include "exchange.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace exchange {

inline constexpr RequestId::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : transaction_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestId::RequestId(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestIdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestIdDefaultTypeInternal() {}
  union {
    RequestId _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestIdDefaultTypeInternal _RequestId_default_instance_;

inline constexpr MessageResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : transaction_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MessageResponse::MessageResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageResponseDefaultTypeInternal() {}
  union {
    MessageResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageResponseDefaultTypeInternal _MessageResponse_default_instance_;

inline constexpr ClientRegistrationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : client_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClientRegistrationRequest::ClientRegistrationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClientRegistrationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientRegistrationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientRegistrationRequestDefaultTypeInternal() {}
  union {
    ClientRegistrationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientRegistrationRequestDefaultTypeInternal _ClientRegistrationRequest_default_instance_;

inline constexpr Acknowledge::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : reply_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Acknowledge::Acknowledge(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AcknowledgeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AcknowledgeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AcknowledgeDefaultTypeInternal() {}
  union {
    Acknowledge _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AcknowledgeDefaultTypeInternal _Acknowledge_default_instance_;

inline constexpr MessageRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sender_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        transaction_id_{nullptr},
        receiver_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR MessageRequest::MessageRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MessageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageRequestDefaultTypeInternal() {}
  union {
    MessageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageRequestDefaultTypeInternal _MessageRequest_default_instance_;
}  // namespace exchange
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_exchange_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_exchange_2eproto = nullptr;
const ::uint32_t
    TableStruct_exchange_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::exchange::RequestId, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::exchange::RequestId, _impl_.transaction_id_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _impl_.transaction_id_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _impl_.message_id_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _impl_.sender_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _impl_.receiver_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageRequest, _impl_.message_payload_),
        0,
        ~0u,
        ~0u,
        1,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::exchange::ClientRegistrationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::exchange::ClientRegistrationRequest, _impl_.client_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::exchange::Acknowledge, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::exchange::Acknowledge, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::exchange::Acknowledge, _impl_.reply_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::exchange::MessageResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::exchange::MessageResponse, _impl_.transaction_id_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageResponse, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::exchange::MessageResponse, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::exchange::RequestId)},
        {9, 22, -1, sizeof(::exchange::MessageRequest)},
        {27, -1, -1, sizeof(::exchange::ClientRegistrationRequest)},
        {36, -1, -1, sizeof(::exchange::Acknowledge)},
        {46, -1, -1, sizeof(::exchange::MessageResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::exchange::_RequestId_default_instance_._instance,
    &::exchange::_MessageRequest_default_instance_._instance,
    &::exchange::_ClientRegistrationRequest_default_instance_._instance,
    &::exchange::_Acknowledge_default_instance_._instance,
    &::exchange::_MessageResponse_default_instance_._instance,
};
const char descriptor_table_protodef_exchange_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016exchange.proto\022\010exchange\032\036google/proto"
    "buf/wrappers.proto\"#\n\tRequestId\022\026\n\016trans"
    "action_id\030\001 \001(\t\"\263\001\n\016MessageRequest\0224\n\016tr"
    "ansaction_id\030\001 \001(\0132\034.google.protobuf.Str"
    "ingValue\022\022\n\nmessage_id\030\002 \001(\t\022\016\n\006sender\030\003"
    " \001(\t\022.\n\010receiver\030\004 \001(\0132\034.google.protobuf"
    ".StringValue\022\027\n\017message_payload\030\005 \001(\t\".\n"
    "\031ClientRegistrationRequest\022\021\n\tclient_id\030"
    "\001 \001(\t\"-\n\013Acknowledge\022\017\n\007success\030\001 \001(\010\022\r\n"
    "\005reply\030\002 \001(\t\"G\n\017MessageResponse\022\026\n\016trans"
    "action_id\030\001 \001(\t\022\016\n\006result\030\002 \001(\010\022\014\n\004data\030"
    "\003 \001(\t2\346\001\n\017ExchangeService\022>\n\013SendMessage"
    "\022\030.exchange.MessageRequest\032\025.exchange.Ac"
    "knowledge\022@\n\014SendResponse\022\031.exchange.Mes"
    "sageResponse\032\025.exchange.Acknowledge\022Q\n\016R"
    "egisterClient\022#.exchange.ClientRegistrat"
    "ionRequest\032\030.exchange.MessageRequest0\001b\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_exchange_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::absl::once_flag descriptor_table_exchange_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_exchange_2eproto = {
    false,
    false,
    686,
    descriptor_table_protodef_exchange_2eproto,
    "exchange.proto",
    &descriptor_table_exchange_2eproto_once,
    descriptor_table_exchange_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_exchange_2eproto::offsets,
    file_level_enum_descriptors_exchange_2eproto,
    file_level_service_descriptors_exchange_2eproto,
};
namespace exchange {
// ===================================================================

class RequestId::_Internal {
 public:
};

RequestId::RequestId(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:exchange.RequestId)
}
inline PROTOBUF_NDEBUG_INLINE RequestId::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::exchange::RequestId& from_msg)
      : transaction_id_(arena, from.transaction_id_),
        _cached_size_{0} {}

RequestId::RequestId(
    ::google::protobuf::Arena* arena,
    const RequestId& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestId* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:exchange.RequestId)
}
inline PROTOBUF_NDEBUG_INLINE RequestId::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : transaction_id_(arena),
        _cached_size_{0} {}

inline void RequestId::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestId::~RequestId() {
  // @@protoc_insertion_point(destructor:exchange.RequestId)
  SharedDtor(*this);
}
inline void RequestId::SharedDtor(MessageLite& self) {
  RequestId& this_ = static_cast<RequestId&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.transaction_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RequestId::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RequestId(arena);
}
constexpr auto RequestId::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RequestId),
                                            alignof(RequestId));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RequestId::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RequestId_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RequestId::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RequestId>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RequestId::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RequestId>(), &RequestId::ByteSizeLong,
            &RequestId::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RequestId, _impl_._cached_size_),
        false,
    },
    &RequestId::kDescriptorMethods,
    &descriptor_table_exchange_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RequestId::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> RequestId::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::exchange::RequestId>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string transaction_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestId, _impl_.transaction_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string transaction_id = 1;
    {PROTOBUF_FIELD_OFFSET(RequestId, _impl_.transaction_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\16\0\0\0\0\0\0"
    "exchange.RequestId"
    "transaction_id"
  }},
};

PROTOBUF_NOINLINE void RequestId::Clear() {
// @@protoc_insertion_point(message_clear_start:exchange.RequestId)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.transaction_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RequestId::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RequestId& this_ = static_cast<const RequestId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RequestId::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RequestId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:exchange.RequestId)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string transaction_id = 1;
          if (!this_._internal_transaction_id().empty()) {
            const std::string& _s = this_._internal_transaction_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.RequestId.transaction_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:exchange.RequestId)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RequestId::ByteSizeLong(const MessageLite& base) {
          const RequestId& this_ = static_cast<const RequestId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RequestId::ByteSizeLong() const {
          const RequestId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:exchange.RequestId)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string transaction_id = 1;
            if (!this_._internal_transaction_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_transaction_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RequestId::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestId*>(&to_msg);
  auto& from = static_cast<const RequestId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:exchange.RequestId)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_transaction_id().empty()) {
    _this->_internal_set_transaction_id(from._internal_transaction_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestId::CopyFrom(const RequestId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:exchange.RequestId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestId::InternalSwap(RequestId* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.transaction_id_, &other->_impl_.transaction_id_, arena);
}

::google::protobuf::Metadata RequestId::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessageRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MessageRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_._has_bits_);
};

void MessageRequest::clear_transaction_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.transaction_id_ != nullptr) _impl_.transaction_id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void MessageRequest::clear_receiver() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.receiver_ != nullptr) _impl_.receiver_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
MessageRequest::MessageRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:exchange.MessageRequest)
}
inline PROTOBUF_NDEBUG_INLINE MessageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::exchange::MessageRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_id_(arena, from.message_id_),
        sender_(arena, from.sender_),
        message_payload_(arena, from.message_payload_) {}

MessageRequest::MessageRequest(
    ::google::protobuf::Arena* arena,
    const MessageRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MessageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.transaction_id_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::StringValue>(
                              arena, *from._impl_.transaction_id_)
                        : nullptr;
  _impl_.receiver_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::StringValue>(
                              arena, *from._impl_.receiver_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:exchange.MessageRequest)
}
inline PROTOBUF_NDEBUG_INLINE MessageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        message_id_(arena),
        sender_(arena),
        message_payload_(arena) {}

inline void MessageRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, transaction_id_),
           0,
           offsetof(Impl_, receiver_) -
               offsetof(Impl_, transaction_id_) +
               sizeof(Impl_::receiver_));
}
MessageRequest::~MessageRequest() {
  // @@protoc_insertion_point(destructor:exchange.MessageRequest)
  SharedDtor(*this);
}
inline void MessageRequest::SharedDtor(MessageLite& self) {
  MessageRequest& this_ = static_cast<MessageRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_id_.Destroy();
  this_._impl_.sender_.Destroy();
  this_._impl_.message_payload_.Destroy();
  delete this_._impl_.transaction_id_;
  delete this_._impl_.receiver_;
  this_._impl_.~Impl_();
}

inline void* MessageRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MessageRequest(arena);
}
constexpr auto MessageRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MessageRequest),
                                            alignof(MessageRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MessageRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MessageRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MessageRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MessageRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MessageRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MessageRequest>(), &MessageRequest::ByteSizeLong,
            &MessageRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_._cached_size_),
        false,
    },
    &MessageRequest::kDescriptorMethods,
    &descriptor_table_exchange_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MessageRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 63, 2> MessageRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::exchange::MessageRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .google.protobuf.StringValue transaction_id = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.transaction_id_)}},
    // string message_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.message_id_)}},
    // string sender = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.sender_)}},
    // .google.protobuf.StringValue receiver = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.receiver_)}},
    // string message_payload = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.message_payload_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.StringValue transaction_id = 1;
    {PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.transaction_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string message_id = 2;
    {PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.message_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string sender = 3;
    {PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.sender_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.StringValue receiver = 4;
    {PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.receiver_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string message_payload = 5;
    {PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.message_payload_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::StringValue>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::StringValue>()},
  }}, {{
    "\27\0\12\6\0\17\0\0"
    "exchange.MessageRequest"
    "message_id"
    "sender"
    "message_payload"
  }},
};

PROTOBUF_NOINLINE void MessageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:exchange.MessageRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_id_.ClearToEmpty();
  _impl_.sender_.ClearToEmpty();
  _impl_.message_payload_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.transaction_id_ != nullptr);
      _impl_.transaction_id_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.receiver_ != nullptr);
      _impl_.receiver_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MessageRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MessageRequest& this_ = static_cast<const MessageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MessageRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MessageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:exchange.MessageRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.StringValue transaction_id = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.transaction_id_, this_._impl_.transaction_id_->GetCachedSize(), target,
                stream);
          }

          // string message_id = 2;
          if (!this_._internal_message_id().empty()) {
            const std::string& _s = this_._internal_message_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.MessageRequest.message_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string sender = 3;
          if (!this_._internal_sender().empty()) {
            const std::string& _s = this_._internal_sender();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.MessageRequest.sender");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // .google.protobuf.StringValue receiver = 4;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.receiver_, this_._impl_.receiver_->GetCachedSize(), target,
                stream);
          }

          // string message_payload = 5;
          if (!this_._internal_message_payload().empty()) {
            const std::string& _s = this_._internal_message_payload();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.MessageRequest.message_payload");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:exchange.MessageRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MessageRequest::ByteSizeLong(const MessageLite& base) {
          const MessageRequest& this_ = static_cast<const MessageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MessageRequest::ByteSizeLong() const {
          const MessageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:exchange.MessageRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message_id = 2;
            if (!this_._internal_message_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message_id());
            }
            // string sender = 3;
            if (!this_._internal_sender().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sender());
            }
            // string message_payload = 5;
            if (!this_._internal_message_payload().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message_payload());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .google.protobuf.StringValue transaction_id = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.transaction_id_);
            }
            // .google.protobuf.StringValue receiver = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.receiver_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MessageRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MessageRequest*>(&to_msg);
  auto& from = static_cast<const MessageRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:exchange.MessageRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_id().empty()) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  if (!from._internal_sender().empty()) {
    _this->_internal_set_sender(from._internal_sender());
  }
  if (!from._internal_message_payload().empty()) {
    _this->_internal_set_message_payload(from._internal_message_payload());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.transaction_id_ != nullptr);
      if (_this->_impl_.transaction_id_ == nullptr) {
        _this->_impl_.transaction_id_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::StringValue>(arena, *from._impl_.transaction_id_);
      } else {
        _this->_impl_.transaction_id_->MergeFrom(*from._impl_.transaction_id_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.receiver_ != nullptr);
      if (_this->_impl_.receiver_ == nullptr) {
        _this->_impl_.receiver_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::StringValue>(arena, *from._impl_.receiver_);
      } else {
        _this->_impl_.receiver_->MergeFrom(*from._impl_.receiver_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageRequest::CopyFrom(const MessageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:exchange.MessageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MessageRequest::InternalSwap(MessageRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_id_, &other->_impl_.message_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_, &other->_impl_.sender_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_payload_, &other->_impl_.message_payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.receiver_)
      + sizeof(MessageRequest::_impl_.receiver_)
      - PROTOBUF_FIELD_OFFSET(MessageRequest, _impl_.transaction_id_)>(
          reinterpret_cast<char*>(&_impl_.transaction_id_),
          reinterpret_cast<char*>(&other->_impl_.transaction_id_));
}

::google::protobuf::Metadata MessageRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ClientRegistrationRequest::_Internal {
 public:
};

ClientRegistrationRequest::ClientRegistrationRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:exchange.ClientRegistrationRequest)
}
inline PROTOBUF_NDEBUG_INLINE ClientRegistrationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::exchange::ClientRegistrationRequest& from_msg)
      : client_id_(arena, from.client_id_),
        _cached_size_{0} {}

ClientRegistrationRequest::ClientRegistrationRequest(
    ::google::protobuf::Arena* arena,
    const ClientRegistrationRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClientRegistrationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:exchange.ClientRegistrationRequest)
}
inline PROTOBUF_NDEBUG_INLINE ClientRegistrationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : client_id_(arena),
        _cached_size_{0} {}

inline void ClientRegistrationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClientRegistrationRequest::~ClientRegistrationRequest() {
  // @@protoc_insertion_point(destructor:exchange.ClientRegistrationRequest)
  SharedDtor(*this);
}
inline void ClientRegistrationRequest::SharedDtor(MessageLite& self) {
  ClientRegistrationRequest& this_ = static_cast<ClientRegistrationRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.client_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ClientRegistrationRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ClientRegistrationRequest(arena);
}
constexpr auto ClientRegistrationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ClientRegistrationRequest),
                                            alignof(ClientRegistrationRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ClientRegistrationRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ClientRegistrationRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ClientRegistrationRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ClientRegistrationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ClientRegistrationRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ClientRegistrationRequest>(), &ClientRegistrationRequest::ByteSizeLong,
            &ClientRegistrationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ClientRegistrationRequest, _impl_._cached_size_),
        false,
    },
    &ClientRegistrationRequest::kDescriptorMethods,
    &descriptor_table_exchange_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ClientRegistrationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 52, 2> ClientRegistrationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::exchange::ClientRegistrationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string client_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClientRegistrationRequest, _impl_.client_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_id = 1;
    {PROTOBUF_FIELD_OFFSET(ClientRegistrationRequest, _impl_.client_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\11\0\0\0\0\0\0"
    "exchange.ClientRegistrationRequest"
    "client_id"
  }},
};

PROTOBUF_NOINLINE void ClientRegistrationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:exchange.ClientRegistrationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ClientRegistrationRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ClientRegistrationRequest& this_ = static_cast<const ClientRegistrationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ClientRegistrationRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ClientRegistrationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:exchange.ClientRegistrationRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string client_id = 1;
          if (!this_._internal_client_id().empty()) {
            const std::string& _s = this_._internal_client_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.ClientRegistrationRequest.client_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:exchange.ClientRegistrationRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ClientRegistrationRequest::ByteSizeLong(const MessageLite& base) {
          const ClientRegistrationRequest& this_ = static_cast<const ClientRegistrationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ClientRegistrationRequest::ByteSizeLong() const {
          const ClientRegistrationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:exchange.ClientRegistrationRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string client_id = 1;
            if (!this_._internal_client_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_client_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ClientRegistrationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ClientRegistrationRequest*>(&to_msg);
  auto& from = static_cast<const ClientRegistrationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:exchange.ClientRegistrationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClientRegistrationRequest::CopyFrom(const ClientRegistrationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:exchange.ClientRegistrationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClientRegistrationRequest::InternalSwap(ClientRegistrationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_id_, &other->_impl_.client_id_, arena);
}

::google::protobuf::Metadata ClientRegistrationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Acknowledge::_Internal {
 public:
};

Acknowledge::Acknowledge(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:exchange.Acknowledge)
}
inline PROTOBUF_NDEBUG_INLINE Acknowledge::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::exchange::Acknowledge& from_msg)
      : reply_(arena, from.reply_),
        _cached_size_{0} {}

Acknowledge::Acknowledge(
    ::google::protobuf::Arena* arena,
    const Acknowledge& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Acknowledge* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:exchange.Acknowledge)
}
inline PROTOBUF_NDEBUG_INLINE Acknowledge::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : reply_(arena),
        _cached_size_{0} {}

inline void Acknowledge::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
Acknowledge::~Acknowledge() {
  // @@protoc_insertion_point(destructor:exchange.Acknowledge)
  SharedDtor(*this);
}
inline void Acknowledge::SharedDtor(MessageLite& self) {
  Acknowledge& this_ = static_cast<Acknowledge&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reply_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Acknowledge::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Acknowledge(arena);
}
constexpr auto Acknowledge::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Acknowledge),
                                            alignof(Acknowledge));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Acknowledge::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Acknowledge_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Acknowledge::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Acknowledge>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Acknowledge::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Acknowledge>(), &Acknowledge::ByteSizeLong,
            &Acknowledge::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_._cached_size_),
        false,
    },
    &Acknowledge::kDescriptorMethods,
    &descriptor_table_exchange_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Acknowledge::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> Acknowledge::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::exchange::Acknowledge>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string reply = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_.reply_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Acknowledge, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string reply = 2;
    {PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_.reply_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\0\5\0\0\0\0\0"
    "exchange.Acknowledge"
    "reply"
  }},
};

PROTOBUF_NOINLINE void Acknowledge::Clear() {
// @@protoc_insertion_point(message_clear_start:exchange.Acknowledge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reply_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Acknowledge::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Acknowledge& this_ = static_cast<const Acknowledge&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Acknowledge::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Acknowledge& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:exchange.Acknowledge)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          // string reply = 2;
          if (!this_._internal_reply().empty()) {
            const std::string& _s = this_._internal_reply();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.Acknowledge.reply");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:exchange.Acknowledge)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Acknowledge::ByteSizeLong(const MessageLite& base) {
          const Acknowledge& this_ = static_cast<const Acknowledge&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Acknowledge::ByteSizeLong() const {
          const Acknowledge& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:exchange.Acknowledge)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string reply = 2;
            if (!this_._internal_reply().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_reply());
            }
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Acknowledge::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Acknowledge*>(&to_msg);
  auto& from = static_cast<const Acknowledge&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:exchange.Acknowledge)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reply().empty()) {
    _this->_internal_set_reply(from._internal_reply());
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Acknowledge::CopyFrom(const Acknowledge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:exchange.Acknowledge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Acknowledge::InternalSwap(Acknowledge* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reply_, &other->_impl_.reply_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata Acknowledge::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessageResponse::_Internal {
 public:
};

MessageResponse::MessageResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:exchange.MessageResponse)
}
inline PROTOBUF_NDEBUG_INLINE MessageResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::exchange::MessageResponse& from_msg)
      : transaction_id_(arena, from.transaction_id_),
        data_(arena, from.data_),
        _cached_size_{0} {}

MessageResponse::MessageResponse(
    ::google::protobuf::Arena* arena,
    const MessageResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MessageResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:exchange.MessageResponse)
}
inline PROTOBUF_NDEBUG_INLINE MessageResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : transaction_id_(arena),
        data_(arena),
        _cached_size_{0} {}

inline void MessageResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
MessageResponse::~MessageResponse() {
  // @@protoc_insertion_point(destructor:exchange.MessageResponse)
  SharedDtor(*this);
}
inline void MessageResponse::SharedDtor(MessageLite& self) {
  MessageResponse& this_ = static_cast<MessageResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.transaction_id_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* MessageResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MessageResponse(arena);
}
constexpr auto MessageResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MessageResponse),
                                            alignof(MessageResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MessageResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MessageResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MessageResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MessageResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MessageResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MessageResponse>(), &MessageResponse::ByteSizeLong,
            &MessageResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_._cached_size_),
        false,
    },
    &MessageResponse::kDescriptorMethods,
    &descriptor_table_exchange_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MessageResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 51, 2> MessageResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::exchange::MessageResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string transaction_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_.transaction_id_)}},
    // bool result = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MessageResponse, _impl_.result_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_.result_)}},
    // string data = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string transaction_id = 1;
    {PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_.transaction_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool result = 2;
    {PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string data = 3;
    {PROTOBUF_FIELD_OFFSET(MessageResponse, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\16\0\4\0\0\0\0"
    "exchange.MessageResponse"
    "transaction_id"
    "data"
  }},
};

PROTOBUF_NOINLINE void MessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:exchange.MessageResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.transaction_id_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _impl_.result_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MessageResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MessageResponse& this_ = static_cast<const MessageResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MessageResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MessageResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:exchange.MessageResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string transaction_id = 1;
          if (!this_._internal_transaction_id().empty()) {
            const std::string& _s = this_._internal_transaction_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.MessageResponse.transaction_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool result = 2;
          if (this_._internal_result() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_result(), target);
          }

          // string data = 3;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "exchange.MessageResponse.data");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:exchange.MessageResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MessageResponse::ByteSizeLong(const MessageLite& base) {
          const MessageResponse& this_ = static_cast<const MessageResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MessageResponse::ByteSizeLong() const {
          const MessageResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:exchange.MessageResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string transaction_id = 1;
            if (!this_._internal_transaction_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_transaction_id());
            }
            // string data = 3;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data());
            }
            // bool result = 2;
            if (this_._internal_result() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MessageResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MessageResponse*>(&to_msg);
  auto& from = static_cast<const MessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:exchange.MessageResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_transaction_id().empty()) {
    _this->_internal_set_transaction_id(from._internal_transaction_id());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageResponse::CopyFrom(const MessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:exchange.MessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MessageResponse::InternalSwap(MessageResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.transaction_id_, &other->_impl_.transaction_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
        swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata MessageResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace exchange
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_exchange_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
